export default {
  CHANGE_EVENT:               'CHANGE_EVENT',
  SELECTED_TIME_CHANGE:       'SELECTED_TIME_CHANGE',
  CHANGE_SETTINGS_OPEN_STATE: 'CHANGE_SETTINGS_OPEN_STATE',
  REMOVE_TIMEZONE:            'REMOVE_TIMEZONE',
  ADD_TIMEZONE:               'ADD_TIMEZONE'
}
